services:
  web:
    image: ghcr.io/kosenkomichael/ois-csharp-example:latest
    container_name: ois-csharp-app
    ports:
      - "8181:8181"
    environment:
      - ConnectionStrings__Postgres=Host=db;User Id=postgres;Password=123;Database=postgres;Port=5432;Pooling=false
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: ois-csharp-db
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
