services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  csharp-app:
    image: ghcr.io/kosenkomichael/ois-csharp-example:latest
    ports:
      - "8181:8181"
    environment:
      - ConnectionStrings__Postgres=Host=db;User Id=exampleuser;Password=examplepass;Database=postgres;Port=5432;Pooling=false
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:
