services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  csharp-app:
    image: ghcr.io/kosenkomichael/ois-csharp-example:latest
    container_name: csharp-app
    ports:
      - "8181:5000"
    environment:
      ConnectionStrings__Postgres: "Host=postgres-db;Port=5432;Database=exampledb;Username=exampleuser;Password=examplepass"
    depends_on:
      - postgres-db
    restart: unless-stopped

volumes:
  db-data:
